package com.aipo.orm.model.account.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.account.EipTAclRole;

/**
 * Class _EipTAclPortletFeature was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTAclPortletFeature extends CayenneDataObject {

    public static final String ACL_TYPE_PROPERTY = "aclType";
    public static final String FEATURE_ALIAS_NAME_PROPERTY = "featureAliasName";
    public static final String FEATURE_NAME_PROPERTY = "featureName";
    public static final String EIP_TACL_ROLE_PROPERTY = "eipTAclRole";

    public static final String FEATURE_ID_PK_COLUMN = "FEATURE_ID";

    public void setAclType(Integer aclType) {
        writeProperty("aclType", aclType);
    }
    public Integer getAclType() {
        return (Integer)readProperty("aclType");
    }

    public void setFeatureAliasName(String featureAliasName) {
        writeProperty("featureAliasName", featureAliasName);
    }
    public String getFeatureAliasName() {
        return (String)readProperty("featureAliasName");
    }

    public void setFeatureName(String featureName) {
        writeProperty("featureName", featureName);
    }
    public String getFeatureName() {
        return (String)readProperty("featureName");
    }

    public void addToEipTAclRole(EipTAclRole obj) {
        addToManyTarget("eipTAclRole", obj, true);
    }
    public void removeFromEipTAclRole(EipTAclRole obj) {
        removeToManyTarget("eipTAclRole", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTAclRole> getEipTAclRole() {
        return (List<EipTAclRole>)readProperty("eipTAclRole");
    }


}
