package com.aipo.orm.model.account.auto;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.security.TurbineUser;

/**
 * Class _EipMUserPosition was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipMUserPosition extends CayenneDataObject {

    public static final String POSITION_PROPERTY = "position";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String ID_PK_COLUMN = "ID";

    public void setPosition(Integer position) {
        writeProperty("position", position);
    }
    public Integer getPosition() {
        return (Integer)readProperty("position");
    }

    public void setTurbineUser(TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public TurbineUser getTurbineUser() {
        return (TurbineUser)readProperty("turbineUser");
    }


}
