package com.aipo.orm.model.account.auto;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.account.EipTAclRole;
import com.aipo.orm.model.security.TurbineUser;

/**
 * Class _EipTAclUserRoleMap was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTAclUserRoleMap extends CayenneDataObject {

    public static final String ROLE_ID_PROPERTY = "roleId";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TACL_ROLE_PROPERTY = "eipTAclRole";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String ID_PK_COLUMN = "ID";

    public void setRoleId(Integer roleId) {
        writeProperty("roleId", roleId);
    }
    public Integer getRoleId() {
        return (Integer)readProperty("roleId");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setEipTAclRole(EipTAclRole eipTAclRole) {
        setToOneTarget("eipTAclRole", eipTAclRole, true);
    }

    public EipTAclRole getEipTAclRole() {
        return (EipTAclRole)readProperty("eipTAclRole");
    }


    public void setTurbineUser(TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public TurbineUser getTurbineUser() {
        return (TurbineUser)readProperty("turbineUser");
    }


}
