/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2011 Aimluck,Inc.
 * http://www.aipo.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aipo.orm.model.account.auto;

import java.util.List;

/** Class _EipTAclPortletFeature was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTAclPortletFeature extends org.apache.cayenne.CayenneDataObject {

    public static final String ACL_TYPE_PROPERTY = "aclType";
    public static final String FEATURE_ALIAS_NAME_PROPERTY = "featureAliasName";
    public static final String FEATURE_NAME_PROPERTY = "featureName";
    public static final String EIP_TACL_ROLE_PROPERTY = "eipTAclRole";

    public static final String FEATURE_ID_PK_COLUMN = "FEATURE_ID";

    public void setAclType(Integer aclType) {
        writeProperty("aclType", aclType);
    }
    public Integer getAclType() {
        return (Integer)readProperty("aclType");
    }
    
    
    public void setFeatureAliasName(String featureAliasName) {
        writeProperty("featureAliasName", featureAliasName);
    }
    public String getFeatureAliasName() {
        return (String)readProperty("featureAliasName");
    }
    
    
    public void setFeatureName(String featureName) {
        writeProperty("featureName", featureName);
    }
    public String getFeatureName() {
        return (String)readProperty("featureName");
    }
    
    
    public void addToEipTAclRole(com.aipo.orm.model.account.EipTAclRole obj) {
        addToManyTarget("eipTAclRole", obj, true);
    }
    public void removeFromEipTAclRole(com.aipo.orm.model.account.EipTAclRole obj) {
        removeToManyTarget("eipTAclRole", obj, true);
    }
    public List getEipTAclRole() {
        return (List)readProperty("eipTAclRole");
    }
    
    
}
