package com.aipo.orm.model.account.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _EipMPosition was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipMPosition extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String POSITION_NAME_PROPERTY = "positionName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";

    public static final String POSITION_ID_PK_COLUMN = "POSITION_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setPositionName(String positionName) {
        writeProperty("positionName", positionName);
    }
    public String getPositionName() {
        return (String)readProperty("positionName");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

}
