package com.aipo.orm.model.social.auto;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.social.Activity;

/**
 * Class _ActivityMap was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ActivityMap extends CayenneDataObject {

    public static final String IS_READ_PROPERTY = "isRead";
    public static final String LOGIN_NAME_PROPERTY = "loginName";
    public static final String ACTIVITY_PROPERTY = "activity";

    public static final String ID_PK_COLUMN = "ID";

    public void setIsRead(Integer isRead) {
        writeProperty("isRead", isRead);
    }
    public Integer getIsRead() {
        return (Integer)readProperty("isRead");
    }

    public void setLoginName(String loginName) {
        writeProperty("loginName", loginName);
    }
    public String getLoginName() {
        return (String)readProperty("loginName");
    }

    public void setActivity(Activity activity) {
        setToOneTarget("activity", activity, true);
    }

    public Activity getActivity() {
        return (Activity)readProperty("activity");
    }


}
