package com.aipo.orm.model.social.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ContainerConfig was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContainerConfig extends CayenneDataObject {

    public static final String KEY_PROPERTY = "key";
    public static final String VALUE_PROPERTY = "value";

    public static final String ID_PK_COLUMN = "ID";

    public void setKey(String key) {
        writeProperty("key", key);
    }
    public String getKey() {
        return (String)readProperty("key");
    }

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }

}
