package com.aipo.orm.model.social.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ModuleId was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ModuleId extends CayenneDataObject {


    public static final String ID_PK_COLUMN = "ID";

}
