package com.aipo.orm.model.social.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _OAuth2Client was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OAuth2Client extends CayenneDataObject {

    public static final String CLIENT_ID_PROPERTY = "clientId";
    public static final String CLIENT_SECRET_PROPERTY = "clientSecret";
    public static final String CLIENT_TYPE_PROPERTY = "clientType";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String FLOW_PROPERTY = "flow";
    public static final String ICON_URL_PROPERTY = "iconUrl";
    public static final String REDIRECT_URI_PROPERTY = "redirectUri";
    public static final String TITLE_PROPERTY = "title";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";

    public static final String ID_PK_COLUMN = "ID";

    public void setClientId(String clientId) {
        writeProperty("clientId", clientId);
    }
    public String getClientId() {
        return (String)readProperty("clientId");
    }

    public void setClientSecret(String clientSecret) {
        writeProperty("clientSecret", clientSecret);
    }
    public String getClientSecret() {
        return (String)readProperty("clientSecret");
    }

    public void setClientType(String clientType) {
        writeProperty("clientType", clientType);
    }
    public String getClientType() {
        return (String)readProperty("clientType");
    }

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setFlow(String flow) {
        writeProperty("flow", flow);
    }
    public String getFlow() {
        return (String)readProperty("flow");
    }

    public void setIconUrl(String iconUrl) {
        writeProperty("iconUrl", iconUrl);
    }
    public String getIconUrl() {
        return (String)readProperty("iconUrl");
    }

    public void setRedirectUri(String redirectUri) {
        writeProperty("redirectUri", redirectUri);
    }
    public String getRedirectUri() {
        return (String)readProperty("redirectUri");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

}
