/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2011 Aimluck,Inc.
 * http://www.aipo.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aipo.orm.model.social.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _OAuthToken was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OAuthToken extends CayenneDataObject {

    public static final String ACCESS_TOKEN_PROPERTY = "accessToken";
    public static final String KEY_PROPERTY = "key";
    public static final String SESSION_HANDLE_PROPERTY = "sessionHandle";
    public static final String TOKEN_EXPIRE_MILIS_PROPERTY = "tokenExpireMilis";
    public static final String TOKEN_SECRET_PROPERTY = "tokenSecret";

    public static final String KEY_PK_COLUMN = "KEY";

    public void setAccessToken(String accessToken) {
        writeProperty("accessToken", accessToken);
    }
    public String getAccessToken() {
        return (String)readProperty("accessToken");
    }

    public void setKey(Integer key) {
        writeProperty("key", key);
    }
    public Integer getKey() {
        return (Integer)readProperty("key");
    }

    public void setSessionHandle(String sessionHandle) {
        writeProperty("sessionHandle", sessionHandle);
    }
    public String getSessionHandle() {
        return (String)readProperty("sessionHandle");
    }

    public void setTokenExpireMilis(Integer tokenExpireMilis) {
        writeProperty("tokenExpireMilis", tokenExpireMilis);
    }
    public Integer getTokenExpireMilis() {
        return (Integer)readProperty("tokenExpireMilis");
    }

    public void setTokenSecret(String tokenSecret) {
        writeProperty("tokenSecret", tokenSecret);
    }
    public String getTokenSecret() {
        return (String)readProperty("tokenSecret");
    }

}
