package com.aipo.orm.model.portlet.auto;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipMAddressGroup;
import com.aipo.orm.model.portlet.EipMAddressbook;

/**
 * Class _EipTAddressbookGroupMap was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTAddressbookGroupMap extends CayenneDataObject {

    public static final String ADDRESS_ID_PROPERTY = "addressId";
    public static final String EIP_MADDRESSBOOK_PROPERTY = "eipMAddressbook";
    public static final String EIP_TADDRESS_GROUP_PROPERTY = "eipTAddressGroup";

    public static final String ID_PK_COLUMN = "ID";

    public void setAddressId(Integer addressId) {
        writeProperty("addressId", addressId);
    }
    public Integer getAddressId() {
        return (Integer)readProperty("addressId");
    }

    public void setEipMAddressbook(EipMAddressbook eipMAddressbook) {
        setToOneTarget("eipMAddressbook", eipMAddressbook, true);
    }

    public EipMAddressbook getEipMAddressbook() {
        return (EipMAddressbook)readProperty("eipMAddressbook");
    }


    public void setEipTAddressGroup(EipMAddressGroup eipTAddressGroup) {
        setToOneTarget("eipTAddressGroup", eipTAddressGroup, true);
    }

    public EipMAddressGroup getEipTAddressGroup() {
        return (EipMAddressGroup)readProperty("eipTAddressGroup");
    }


}
