package com.aipo.orm.model.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _EipTTimecard was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTTimecard extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String REASON_PROPERTY = "reason";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String WORK_DATE_PROPERTY = "workDate";
    public static final String WORK_FLAG_PROPERTY = "workFlag";

    public static final String TIMECARD_ID_PK_COLUMN = "TIMECARD_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setReason(String reason) {
        writeProperty("reason", reason);
    }
    public String getReason() {
        return (String)readProperty("reason");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setWorkDate(Date workDate) {
        writeProperty("workDate", workDate);
    }
    public Date getWorkDate() {
        return (Date)readProperty("workDate");
    }

    public void setWorkFlag(String workFlag) {
        writeProperty("workFlag", workFlag);
    }
    public String getWorkFlag() {
        return (String)readProperty("workFlag");
    }

}
