package com.aipo.orm.model.portlet.auto;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTMsgboardCategory;

/**
 * Class _EipTMsgboardCategoryMap was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTMsgboardCategoryMap extends CayenneDataObject {

    public static final String CATEGORY_ID_PROPERTY = "categoryId";
    public static final String STATUS_PROPERTY = "status";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TMSGBOARD_CATEGORY_PROPERTY = "eipTMsgboardCategory";

    public static final String ID_PK_COLUMN = "ID";

    public void setCategoryId(Integer categoryId) {
        writeProperty("categoryId", categoryId);
    }
    public Integer getCategoryId() {
        return (Integer)readProperty("categoryId");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setEipTMsgboardCategory(EipTMsgboardCategory eipTMsgboardCategory) {
        setToOneTarget("eipTMsgboardCategory", eipTMsgboardCategory, true);
    }

    public EipTMsgboardCategory getEipTMsgboardCategory() {
        return (EipTMsgboardCategory)readProperty("eipTMsgboardCategory");
    }


}
