package com.aipo.orm.model.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _EipTMemo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTMemo extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String MEMO_NAME_PROPERTY = "memoName";
    public static final String NOTE_PROPERTY = "note";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";

    public static final String MEMO_ID_PK_COLUMN = "MEMO_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setMemoName(String memoName) {
        writeProperty("memoName", memoName);
    }
    public String getMemoName() {
        return (String)readProperty("memoName");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

}
