package com.aipo.orm.model.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _EipTExtTimecard was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTExtTimecard extends CayenneDataObject {

    public static final String CLOCK_IN_TIME_PROPERTY = "clockInTime";
    public static final String CLOCK_OUT_TIME_PROPERTY = "clockOutTime";
    public static final String COMEBACK_TIME1_PROPERTY = "comebackTime1";
    public static final String COMEBACK_TIME2_PROPERTY = "comebackTime2";
    public static final String COMEBACK_TIME3_PROPERTY = "comebackTime3";
    public static final String COMEBACK_TIME4_PROPERTY = "comebackTime4";
    public static final String COMEBACK_TIME5_PROPERTY = "comebackTime5";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String OUTGOING_TIME1_PROPERTY = "outgoingTime1";
    public static final String OUTGOING_TIME2_PROPERTY = "outgoingTime2";
    public static final String OUTGOING_TIME3_PROPERTY = "outgoingTime3";
    public static final String OUTGOING_TIME4_PROPERTY = "outgoingTime4";
    public static final String OUTGOING_TIME5_PROPERTY = "outgoingTime5";
    public static final String PUNCH_DATE_PROPERTY = "punchDate";
    public static final String REASON_PROPERTY = "reason";
    public static final String REMARKS_PROPERTY = "remarks";
    public static final String TYPE_PROPERTY = "type";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";

    public static final String TIMECARD_ID_PK_COLUMN = "TIMECARD_ID";

    public void setClockInTime(Date clockInTime) {
        writeProperty("clockInTime", clockInTime);
    }
    public Date getClockInTime() {
        return (Date)readProperty("clockInTime");
    }

    public void setClockOutTime(Date clockOutTime) {
        writeProperty("clockOutTime", clockOutTime);
    }
    public Date getClockOutTime() {
        return (Date)readProperty("clockOutTime");
    }

    public void setComebackTime1(Date comebackTime1) {
        writeProperty("comebackTime1", comebackTime1);
    }
    public Date getComebackTime1() {
        return (Date)readProperty("comebackTime1");
    }

    public void setComebackTime2(Date comebackTime2) {
        writeProperty("comebackTime2", comebackTime2);
    }
    public Date getComebackTime2() {
        return (Date)readProperty("comebackTime2");
    }

    public void setComebackTime3(Date comebackTime3) {
        writeProperty("comebackTime3", comebackTime3);
    }
    public Date getComebackTime3() {
        return (Date)readProperty("comebackTime3");
    }

    public void setComebackTime4(Date comebackTime4) {
        writeProperty("comebackTime4", comebackTime4);
    }
    public Date getComebackTime4() {
        return (Date)readProperty("comebackTime4");
    }

    public void setComebackTime5(Date comebackTime5) {
        writeProperty("comebackTime5", comebackTime5);
    }
    public Date getComebackTime5() {
        return (Date)readProperty("comebackTime5");
    }

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setOutgoingTime1(Date outgoingTime1) {
        writeProperty("outgoingTime1", outgoingTime1);
    }
    public Date getOutgoingTime1() {
        return (Date)readProperty("outgoingTime1");
    }

    public void setOutgoingTime2(Date outgoingTime2) {
        writeProperty("outgoingTime2", outgoingTime2);
    }
    public Date getOutgoingTime2() {
        return (Date)readProperty("outgoingTime2");
    }

    public void setOutgoingTime3(Date outgoingTime3) {
        writeProperty("outgoingTime3", outgoingTime3);
    }
    public Date getOutgoingTime3() {
        return (Date)readProperty("outgoingTime3");
    }

    public void setOutgoingTime4(Date outgoingTime4) {
        writeProperty("outgoingTime4", outgoingTime4);
    }
    public Date getOutgoingTime4() {
        return (Date)readProperty("outgoingTime4");
    }

    public void setOutgoingTime5(Date outgoingTime5) {
        writeProperty("outgoingTime5", outgoingTime5);
    }
    public Date getOutgoingTime5() {
        return (Date)readProperty("outgoingTime5");
    }

    public void setPunchDate(Date punchDate) {
        writeProperty("punchDate", punchDate);
    }
    public Date getPunchDate() {
        return (Date)readProperty("punchDate");
    }

    public void setReason(String reason) {
        writeProperty("reason", reason);
    }
    public String getReason() {
        return (String)readProperty("reason");
    }

    public void setRemarks(String remarks) {
        writeProperty("remarks", remarks);
    }
    public String getRemarks() {
        return (String)readProperty("remarks");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

}
