package com.aipo.orm.model.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTBlogEntry;

/**
 * Class _EipTBlogComment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTBlogComment extends CayenneDataObject {

    public static final String COMMENT_PROPERTY = "comment";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TBLOG_ENTRY_PROPERTY = "eipTBlogEntry";

    public static final String COMMENT_ID_PK_COLUMN = "COMMENT_ID";

    public void setComment(String comment) {
        writeProperty("comment", comment);
    }
    public String getComment() {
        return (String)readProperty("comment");
    }

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setEipTBlogEntry(EipTBlogEntry eipTBlogEntry) {
        setToOneTarget("eipTBlogEntry", eipTBlogEntry, true);
    }

    public EipTBlogEntry getEipTBlogEntry() {
        return (EipTBlogEntry)readProperty("eipTBlogEntry");
    }


}
