package com.aipo.orm.model.portlet.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTCabinetFile;
import com.aipo.orm.model.portlet.EipTCabinetFolderMap;

/**
 * Class _EipTCabinetFolder was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTCabinetFolder extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String CREATE_USER_ID_PROPERTY = "createUserId";
    public static final String FOLDER_NAME_PROPERTY = "folderName";
    public static final String NOTE_PROPERTY = "note";
    public static final String PARENT_ID_PROPERTY = "parentId";
    public static final String PUBLIC_FLAG_PROPERTY = "publicFlag";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String UPDATE_USER_ID_PROPERTY = "updateUserId";
    public static final String EIP_TCABINET_FILES_PROPERTY = "eipTCabinetFiles";
    public static final String EIP_TCABINET_FOLDER_MAP_PROPERTY = "eipTCabinetFolderMap";

    public static final String FOLDER_ID_PK_COLUMN = "FOLDER_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setCreateUserId(Integer createUserId) {
        writeProperty("createUserId", createUserId);
    }
    public Integer getCreateUserId() {
        return (Integer)readProperty("createUserId");
    }

    public void setFolderName(String folderName) {
        writeProperty("folderName", folderName);
    }
    public String getFolderName() {
        return (String)readProperty("folderName");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setParentId(Integer parentId) {
        writeProperty("parentId", parentId);
    }
    public Integer getParentId() {
        return (Integer)readProperty("parentId");
    }

    public void setPublicFlag(String publicFlag) {
        writeProperty("publicFlag", publicFlag);
    }
    public String getPublicFlag() {
        return (String)readProperty("publicFlag");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUpdateUserId(Integer updateUserId) {
        writeProperty("updateUserId", updateUserId);
    }
    public Integer getUpdateUserId() {
        return (Integer)readProperty("updateUserId");
    }

    public void addToEipTCabinetFiles(EipTCabinetFile obj) {
        addToManyTarget("eipTCabinetFiles", obj, true);
    }
    public void removeFromEipTCabinetFiles(EipTCabinetFile obj) {
        removeToManyTarget("eipTCabinetFiles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTCabinetFile> getEipTCabinetFiles() {
        return (List<EipTCabinetFile>)readProperty("eipTCabinetFiles");
    }


    public void addToEipTCabinetFolderMap(EipTCabinetFolderMap obj) {
        addToManyTarget("eipTCabinetFolderMap", obj, true);
    }
    public void removeFromEipTCabinetFolderMap(EipTCabinetFolderMap obj) {
        removeToManyTarget("eipTCabinetFolderMap", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTCabinetFolderMap> getEipTCabinetFolderMap() {
        return (List<EipTCabinetFolderMap>)readProperty("eipTCabinetFolderMap");
    }


}
