package com.aipo.orm.model.portlet.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTMessageFile;
import com.aipo.orm.model.portlet.EipTMessageRead;
import com.aipo.orm.model.portlet.EipTMessageRoom;

/**
 * Class _EipTMessage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTMessage extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String MEMBER_COUNT_PROPERTY = "memberCount";
    public static final String MESSAGE_PROPERTY = "message";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TMESSAGE_FILES_PROPERTY = "eipTMessageFiles";
    public static final String EIP_TMESSAGE_READ_PROPERTY = "eipTMessageRead";
    public static final String EIP_TMESSAGE_ROOM_PROPERTY = "eipTMessageRoom";

    public static final String MESSAGE_ID_PK_COLUMN = "MESSAGE_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setMemberCount(Integer memberCount) {
        writeProperty("memberCount", memberCount);
    }
    public Integer getMemberCount() {
        return (Integer)readProperty("memberCount");
    }

    public void setMessage(String message) {
        writeProperty("message", message);
    }
    public String getMessage() {
        return (String)readProperty("message");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void addToEipTMessageFiles(EipTMessageFile obj) {
        addToManyTarget("eipTMessageFiles", obj, true);
    }
    public void removeFromEipTMessageFiles(EipTMessageFile obj) {
        removeToManyTarget("eipTMessageFiles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTMessageFile> getEipTMessageFiles() {
        return (List<EipTMessageFile>)readProperty("eipTMessageFiles");
    }


    public void addToEipTMessageRead(EipTMessageRead obj) {
        addToManyTarget("eipTMessageRead", obj, true);
    }
    public void removeFromEipTMessageRead(EipTMessageRead obj) {
        removeToManyTarget("eipTMessageRead", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTMessageRead> getEipTMessageRead() {
        return (List<EipTMessageRead>)readProperty("eipTMessageRead");
    }


    public void setEipTMessageRoom(EipTMessageRoom eipTMessageRoom) {
        setToOneTarget("eipTMessageRoom", eipTMessageRoom, true);
    }

    public EipTMessageRoom getEipTMessageRoom() {
        return (EipTMessageRoom)readProperty("eipTMessageRoom");
    }


}
