package com.aipo.orm.model.portlet.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipFacilityGroup;

/**
 * Class _EipMFacility was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipMFacility extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String FACILITY_NAME_PROPERTY = "facilityName";
    public static final String NOTE_PROPERTY = "note";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_FACILITY_GROUP_ARRAY_PROPERTY = "eipFacilityGroupArray";

    public static final String FACILITY_ID_PK_COLUMN = "FACILITY_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setFacilityName(String facilityName) {
        writeProperty("facilityName", facilityName);
    }
    public String getFacilityName() {
        return (String)readProperty("facilityName");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void addToEipFacilityGroupArray(EipFacilityGroup obj) {
        addToManyTarget("eipFacilityGroupArray", obj, true);
    }
    public void removeFromEipFacilityGroupArray(EipFacilityGroup obj) {
        removeToManyTarget("eipFacilityGroupArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipFacilityGroup> getEipFacilityGroupArray() {
        return (List<EipFacilityGroup>)readProperty("eipFacilityGroupArray");
    }


}
