package com.aipo.orm.model.portlet.auto;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipMFacility;
import com.aipo.orm.model.security.TurbineGroup;

/**
 * Class _EipFacilityGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipFacilityGroup extends CayenneDataObject {

    public static final String EIP_MFACILITY_PROPERTY = "eipMFacility";
    public static final String TURBINE_GROUP_PROPERTY = "turbineGroup";

    public static final String ID_PK_COLUMN = "ID";

    public void setEipMFacility(EipMFacility eipMFacility) {
        setToOneTarget("eipMFacility", eipMFacility, true);
    }

    public EipMFacility getEipMFacility() {
        return (EipMFacility)readProperty("eipMFacility");
    }


    public void setTurbineGroup(TurbineGroup turbineGroup) {
        setToOneTarget("turbineGroup", turbineGroup, true);
    }

    public TurbineGroup getTurbineGroup() {
        return (TurbineGroup)readProperty("turbineGroup");
    }


}
