/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2011 Aimluck,Inc.
 * http://www.aipo.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aipo.orm.model.portlet.auto;

import java.util.List;

/** Class _EipTMsgboardCategory was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTMsgboardCategory extends org.apache.cayenne.CayenneDataObject {

    public static final String CATEGORY_NAME_PROPERTY = "categoryName";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String NOTE_PROPERTY = "note";
    public static final String PUBLIC_FLAG_PROPERTY = "publicFlag";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TMSGBOARD_CATEGORY_MAPS_PROPERTY = "eipTMsgboardCategoryMaps";
    public static final String EIP_TMSGBOARD_TOPICS_PROPERTY = "eipTMsgboardTopics";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String CATEGORY_ID_PK_COLUMN = "CATEGORY_ID";

    public void setCategoryName(String categoryName) {
        writeProperty("categoryName", categoryName);
    }
    public String getCategoryName() {
        return (String)readProperty("categoryName");
    }
    
    
    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }
    
    
    public void setPublicFlag(String publicFlag) {
        writeProperty("publicFlag", publicFlag);
    }
    public String getPublicFlag() {
        return (String)readProperty("publicFlag");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void addToEipTMsgboardCategoryMaps(com.aipo.orm.model.portlet.EipTMsgboardCategoryMap obj) {
        addToManyTarget("eipTMsgboardCategoryMaps", obj, true);
    }
    public void removeFromEipTMsgboardCategoryMaps(com.aipo.orm.model.portlet.EipTMsgboardCategoryMap obj) {
        removeToManyTarget("eipTMsgboardCategoryMaps", obj, true);
    }
    public List getEipTMsgboardCategoryMaps() {
        return (List)readProperty("eipTMsgboardCategoryMaps");
    }
    
    
    public void addToEipTMsgboardTopics(com.aipo.orm.model.portlet.EipTMsgboardTopic obj) {
        addToManyTarget("eipTMsgboardTopics", obj, true);
    }
    public void removeFromEipTMsgboardTopics(com.aipo.orm.model.portlet.EipTMsgboardTopic obj) {
        removeToManyTarget("eipTMsgboardTopics", obj, true);
    }
    public List getEipTMsgboardTopics() {
        return (List)readProperty("eipTMsgboardTopics");
    }
    
    
    public void setTurbineUser(com.aipo.orm.model.security.TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public com.aipo.orm.model.security.TurbineUser getTurbineUser() {
        return (com.aipo.orm.model.security.TurbineUser)readProperty("turbineUser");
    } 
    
    
}
