package com.aipo.orm.model.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTWorkflowRequest;

/**
 * Class _EipTWorkflowRequestMap was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTWorkflowRequestMap extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String NOTE_PROPERTY = "note";
    public static final String ORDER_INDEX_PROPERTY = "orderIndex";
    public static final String STATUS_PROPERTY = "status";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TWORKFLOW_REQUEST_PROPERTY = "eipTWorkflowRequest";

    public static final String ID_PK_COLUMN = "ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setOrderIndex(Integer orderIndex) {
        writeProperty("orderIndex", orderIndex);
    }
    public Integer getOrderIndex() {
        return (Integer)readProperty("orderIndex");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setEipTWorkflowRequest(EipTWorkflowRequest eipTWorkflowRequest) {
        setToOneTarget("eipTWorkflowRequest", eipTWorkflowRequest, true);
    }

    public EipTWorkflowRequest getEipTWorkflowRequest() {
        return (EipTWorkflowRequest)readProperty("eipTWorkflowRequest");
    }


}
