/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2011 Aimluck,Inc.
 * http://www.aipo.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aipo.orm.model.portlet.auto;

/** Class _EipTMailFilter was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTMailFilter extends org.apache.cayenne.CayenneDataObject {

    public static final String FILTER_NAME_PROPERTY = "filterName";
    public static final String FILTER_STRING_PROPERTY = "filterString";
    public static final String FILTER_TYPE_PROPERTY = "filterType";
    public static final String SORT_ORDER_PROPERTY = "sortOrder";
    public static final String EIP_MMAIL_ACCOUNT_PROPERTY = "eipMMailAccount";
    public static final String EIP_TMAIL_FOLDER_PROPERTY = "eipTMailFolder";

    public static final String FILTER_ID_PK_COLUMN = "FILTER_ID";

    public void setFilterName(String filterName) {
        writeProperty("filterName", filterName);
    }
    public String getFilterName() {
        return (String)readProperty("filterName");
    }
    
    
    public void setFilterString(String filterString) {
        writeProperty("filterString", filterString);
    }
    public String getFilterString() {
        return (String)readProperty("filterString");
    }
    
    
    public void setFilterType(String filterType) {
        writeProperty("filterType", filterType);
    }
    public String getFilterType() {
        return (String)readProperty("filterType");
    }
    
    
    public void setSortOrder(Integer sortOrder) {
        writeProperty("sortOrder", sortOrder);
    }
    public Integer getSortOrder() {
        return (Integer)readProperty("sortOrder");
    }
    
    
    public void setEipMMailAccount(com.aipo.orm.model.portlet.EipMMailAccount eipMMailAccount) {
        setToOneTarget("eipMMailAccount", eipMMailAccount, true);
    }

    public com.aipo.orm.model.portlet.EipMMailAccount getEipMMailAccount() {
        return (com.aipo.orm.model.portlet.EipMMailAccount)readProperty("eipMMailAccount");
    } 
    
    
    public void setEipTMailFolder(com.aipo.orm.model.portlet.EipTMailFolder eipTMailFolder) {
        setToOneTarget("eipTMailFolder", eipTMailFolder, true);
    }

    public com.aipo.orm.model.portlet.EipTMailFolder getEipTMailFolder() {
        return (com.aipo.orm.model.portlet.EipTMailFolder)readProperty("eipTMailFolder");
    } 
    
    
}
