/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2011 Aimluck,Inc.
 * http://www.aipo.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aipo.orm.model.portlet.auto;

/** Class _EipTNoteMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTNoteMap extends org.apache.cayenne.CayenneDataObject {

    public static final String CONFIRM_DATE_PROPERTY = "confirmDate";
    public static final String DEL_FLG_PROPERTY = "delFlg";
    public static final String NOTE_ID_PROPERTY = "noteId";
    public static final String NOTE_STAT_PROPERTY = "noteStat";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TNOTE_PROPERTY = "eipTNote";

    public static final String ID_PK_COLUMN = "ID";

    public void setConfirmDate(java.util.Date confirmDate) {
        writeProperty("confirmDate", confirmDate);
    }
    public java.util.Date getConfirmDate() {
        return (java.util.Date)readProperty("confirmDate");
    }
    
    
    public void setDelFlg(String delFlg) {
        writeProperty("delFlg", delFlg);
    }
    public String getDelFlg() {
        return (String)readProperty("delFlg");
    }
    
    
    public void setNoteId(Integer noteId) {
        writeProperty("noteId", noteId);
    }
    public Integer getNoteId() {
        return (Integer)readProperty("noteId");
    }
    
    
    public void setNoteStat(String noteStat) {
        writeProperty("noteStat", noteStat);
    }
    public String getNoteStat() {
        return (String)readProperty("noteStat");
    }
    
    
    public void setUserId(String userId) {
        writeProperty("userId", userId);
    }
    public String getUserId() {
        return (String)readProperty("userId");
    }
    
    
    public void setEipTNote(com.aipo.orm.model.portlet.EipTNote eipTNote) {
        setToOneTarget("eipTNote", eipTNote, true);
    }

    public com.aipo.orm.model.portlet.EipTNote getEipTNote() {
        return (com.aipo.orm.model.portlet.EipTNote)readProperty("eipTNote");
    } 
    
    
}
