package com.aipo.orm.model.portlet.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTWorkflowCategory;
import com.aipo.orm.model.portlet.EipTWorkflowFile;
import com.aipo.orm.model.portlet.EipTWorkflowRequestMap;
import com.aipo.orm.model.portlet.EipTWorkflowRoute;

/**
 * Class _EipTWorkflowRequest was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTWorkflowRequest extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String NOTE_PROPERTY = "note";
    public static final String PARENT_ID_PROPERTY = "parentId";
    public static final String PRICE_PROPERTY = "price";
    public static final String PRIORITY_PROPERTY = "priority";
    public static final String PROGRESS_PROPERTY = "progress";
    public static final String REQUEST_NAME_PROPERTY = "requestName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TWORKFLOW_CATEGORY_PROPERTY = "eipTWorkflowCategory";
    public static final String EIP_TWORKFLOW_FILE_PROPERTY = "eipTWorkflowFile";
    public static final String EIP_TWORKFLOW_REQUEST_MAP_PROPERTY = "eipTWorkflowRequestMap";
    public static final String EIP_TWORKFLOW_ROUTE_PROPERTY = "eipTWorkflowRoute";

    public static final String REQUEST_ID_PK_COLUMN = "REQUEST_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setParentId(Integer parentId) {
        writeProperty("parentId", parentId);
    }
    public Integer getParentId() {
        return (Integer)readProperty("parentId");
    }

    public void setPrice(Long price) {
        writeProperty("price", price);
    }
    public Long getPrice() {
        return (Long)readProperty("price");
    }

    public void setPriority(Short priority) {
        writeProperty("priority", priority);
    }
    public Short getPriority() {
        return (Short)readProperty("priority");
    }

    public void setProgress(String progress) {
        writeProperty("progress", progress);
    }
    public String getProgress() {
        return (String)readProperty("progress");
    }

    public void setRequestName(String requestName) {
        writeProperty("requestName", requestName);
    }
    public String getRequestName() {
        return (String)readProperty("requestName");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setEipTWorkflowCategory(EipTWorkflowCategory eipTWorkflowCategory) {
        setToOneTarget("eipTWorkflowCategory", eipTWorkflowCategory, true);
    }

    public EipTWorkflowCategory getEipTWorkflowCategory() {
        return (EipTWorkflowCategory)readProperty("eipTWorkflowCategory");
    }


    public void addToEipTWorkflowFile(EipTWorkflowFile obj) {
        addToManyTarget("eipTWorkflowFile", obj, true);
    }
    public void removeFromEipTWorkflowFile(EipTWorkflowFile obj) {
        removeToManyTarget("eipTWorkflowFile", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTWorkflowFile> getEipTWorkflowFile() {
        return (List<EipTWorkflowFile>)readProperty("eipTWorkflowFile");
    }


    public void addToEipTWorkflowRequestMap(EipTWorkflowRequestMap obj) {
        addToManyTarget("eipTWorkflowRequestMap", obj, true);
    }
    public void removeFromEipTWorkflowRequestMap(EipTWorkflowRequestMap obj) {
        removeToManyTarget("eipTWorkflowRequestMap", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTWorkflowRequestMap> getEipTWorkflowRequestMap() {
        return (List<EipTWorkflowRequestMap>)readProperty("eipTWorkflowRequestMap");
    }


    public void setEipTWorkflowRoute(EipTWorkflowRoute eipTWorkflowRoute) {
        setToOneTarget("eipTWorkflowRoute", eipTWorkflowRoute, true);
    }

    public EipTWorkflowRoute getEipTWorkflowRoute() {
        return (EipTWorkflowRoute)readProperty("eipTWorkflowRoute");
    }


}
