package com.aipo.orm.model.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _EipTWhatsNew was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTWhatsNew extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String ENTITY_ID_PROPERTY = "entityId";
    public static final String PARENT_ID_PROPERTY = "parentId";
    public static final String PORTLET_TYPE_PROPERTY = "portletType";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";

    public static final String WHATSNEW_ID_PK_COLUMN = "WHATSNEW_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setEntityId(Integer entityId) {
        writeProperty("entityId", entityId);
    }
    public Integer getEntityId() {
        return (Integer)readProperty("entityId");
    }

    public void setParentId(Integer parentId) {
        writeProperty("parentId", parentId);
    }
    public Integer getParentId() {
        return (Integer)readProperty("parentId");
    }

    public void setPortletType(Integer portletType) {
        writeProperty("portletType", portletType);
    }
    public Integer getPortletType() {
        return (Integer)readProperty("portletType");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

}
