package com.aipo.orm.model.portlet.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTBlog;
import com.aipo.orm.model.portlet.EipTBlogComment;
import com.aipo.orm.model.portlet.EipTBlogFile;
import com.aipo.orm.model.portlet.EipTBlogThema;

/**
 * Class _EipTBlogEntry was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTBlogEntry extends CayenneDataObject {

    public static final String ALLOW_COMMENTS_PROPERTY = "allowComments";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String NOTE_PROPERTY = "note";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String TITLE_PROPERTY = "title";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TBLOG_PROPERTY = "eipTBlog";
    public static final String EIP_TBLOG_COMMENTS_PROPERTY = "eipTBlogComments";
    public static final String EIP_TBLOG_FILES_PROPERTY = "eipTBlogFiles";
    public static final String EIP_TBLOG_THEMA_PROPERTY = "eipTBlogThema";

    public static final String ENTRY_ID_PK_COLUMN = "ENTRY_ID";

    public void setAllowComments(String allowComments) {
        writeProperty("allowComments", allowComments);
    }
    public String getAllowComments() {
        return (String)readProperty("allowComments");
    }

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setEipTBlog(EipTBlog eipTBlog) {
        setToOneTarget("eipTBlog", eipTBlog, true);
    }

    public EipTBlog getEipTBlog() {
        return (EipTBlog)readProperty("eipTBlog");
    }


    public void addToEipTBlogComments(EipTBlogComment obj) {
        addToManyTarget("eipTBlogComments", obj, true);
    }
    public void removeFromEipTBlogComments(EipTBlogComment obj) {
        removeToManyTarget("eipTBlogComments", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTBlogComment> getEipTBlogComments() {
        return (List<EipTBlogComment>)readProperty("eipTBlogComments");
    }


    public void addToEipTBlogFiles(EipTBlogFile obj) {
        addToManyTarget("eipTBlogFiles", obj, true);
    }
    public void removeFromEipTBlogFiles(EipTBlogFile obj) {
        removeToManyTarget("eipTBlogFiles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTBlogFile> getEipTBlogFiles() {
        return (List<EipTBlogFile>)readProperty("eipTBlogFiles");
    }


    public void setEipTBlogThema(EipTBlogThema eipTBlogThema) {
        setToOneTarget("eipTBlogThema", eipTBlogThema, true);
    }

    public EipTBlogThema getEipTBlogThema() {
        return (EipTBlogThema)readProperty("eipTBlogThema");
    }


}
