package com.aipo.orm.model.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTBlog;

/**
 * Class _EipTBlogFootmarkMap was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTBlogFootmarkMap extends CayenneDataObject {

    public static final String BLOG_ID_PROPERTY = "blogId";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TBLOG_PROPERTY = "eipTBlog";

    public static final String ID_PK_COLUMN = "ID";

    public void setBlogId(Integer blogId) {
        writeProperty("blogId", blogId);
    }
    public Integer getBlogId() {
        return (Integer)readProperty("blogId");
    }

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setEipTBlog(EipTBlog eipTBlog) {
        setToOneTarget("eipTBlog", eipTBlog, true);
    }

    public EipTBlog getEipTBlog() {
        return (EipTBlog)readProperty("eipTBlog");
    }


}
