package com.aipo.orm.model.portlet.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTBlogEntry;
import com.aipo.orm.model.portlet.EipTBlogFootmarkMap;

/**
 * Class _EipTBlog was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTBlog extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TBLOG_ENTRYS_PROPERTY = "eipTBlogEntrys";
    public static final String EIP_TBLOG_FOOTMARK_MAPS_PROPERTY = "eipTBlogFootmarkMaps";

    public static final String BLOG_ID_PK_COLUMN = "BLOG_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void addToEipTBlogEntrys(EipTBlogEntry obj) {
        addToManyTarget("eipTBlogEntrys", obj, true);
    }
    public void removeFromEipTBlogEntrys(EipTBlogEntry obj) {
        removeToManyTarget("eipTBlogEntrys", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTBlogEntry> getEipTBlogEntrys() {
        return (List<EipTBlogEntry>)readProperty("eipTBlogEntrys");
    }


    public void addToEipTBlogFootmarkMaps(EipTBlogFootmarkMap obj) {
        addToManyTarget("eipTBlogFootmarkMaps", obj, true);
    }
    public void removeFromEipTBlogFootmarkMaps(EipTBlogFootmarkMap obj) {
        removeToManyTarget("eipTBlogFootmarkMaps", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTBlogFootmarkMap> getEipTBlogFootmarkMaps() {
        return (List<EipTBlogFootmarkMap>)readProperty("eipTBlogFootmarkMaps");
    }


}
