package com.aipo.orm.model.portlet.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTMsgboardCategoryMap;
import com.aipo.orm.model.portlet.EipTMsgboardTopic;
import com.aipo.orm.model.security.TurbineUser;

/**
 * Class _EipTMsgboardCategory was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTMsgboardCategory extends CayenneDataObject {

    public static final String CATEGORY_NAME_PROPERTY = "categoryName";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String NOTE_PROPERTY = "note";
    public static final String PUBLIC_FLAG_PROPERTY = "publicFlag";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TMSGBOARD_CATEGORY_MAPS_PROPERTY = "eipTMsgboardCategoryMaps";
    public static final String EIP_TMSGBOARD_TOPICS_PROPERTY = "eipTMsgboardTopics";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String CATEGORY_ID_PK_COLUMN = "CATEGORY_ID";

    public void setCategoryName(String categoryName) {
        writeProperty("categoryName", categoryName);
    }
    public String getCategoryName() {
        return (String)readProperty("categoryName");
    }

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setPublicFlag(String publicFlag) {
        writeProperty("publicFlag", publicFlag);
    }
    public String getPublicFlag() {
        return (String)readProperty("publicFlag");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void addToEipTMsgboardCategoryMaps(EipTMsgboardCategoryMap obj) {
        addToManyTarget("eipTMsgboardCategoryMaps", obj, true);
    }
    public void removeFromEipTMsgboardCategoryMaps(EipTMsgboardCategoryMap obj) {
        removeToManyTarget("eipTMsgboardCategoryMaps", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTMsgboardCategoryMap> getEipTMsgboardCategoryMaps() {
        return (List<EipTMsgboardCategoryMap>)readProperty("eipTMsgboardCategoryMaps");
    }


    public void addToEipTMsgboardTopics(EipTMsgboardTopic obj) {
        addToManyTarget("eipTMsgboardTopics", obj, true);
    }
    public void removeFromEipTMsgboardTopics(EipTMsgboardTopic obj) {
        removeToManyTarget("eipTMsgboardTopics", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTMsgboardTopic> getEipTMsgboardTopics() {
        return (List<EipTMsgboardTopic>)readProperty("eipTMsgboardTopics");
    }


    public void setTurbineUser(TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public TurbineUser getTurbineUser() {
        return (TurbineUser)readProperty("turbineUser");
    }


}
