package com.aipo.orm.model.portlet.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTAddressbookGroupMap;

/**
 * Class _EipMAddressGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipMAddressGroup extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String GROUP_NAME_PROPERTY = "groupName";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String PUBLIC_FLAG_PROPERTY = "publicFlag";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TADDRESSBOOK_GROUP_MAP_PROPERTY = "eipTAddressbookGroupMap";

    public static final String GROUP_ID_PK_COLUMN = "GROUP_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setGroupName(String groupName) {
        writeProperty("groupName", groupName);
    }
    public String getGroupName() {
        return (String)readProperty("groupName");
    }

    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }

    public void setPublicFlag(String publicFlag) {
        writeProperty("publicFlag", publicFlag);
    }
    public String getPublicFlag() {
        return (String)readProperty("publicFlag");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void addToEipTAddressbookGroupMap(EipTAddressbookGroupMap obj) {
        addToManyTarget("eipTAddressbookGroupMap", obj, true);
    }
    public void removeFromEipTAddressbookGroupMap(EipTAddressbookGroupMap obj) {
        removeToManyTarget("eipTAddressbookGroupMap", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTAddressbookGroupMap> getEipTAddressbookGroupMap() {
        return (List<EipTAddressbookGroupMap>)readProperty("eipTAddressbookGroupMap");
    }


}
