package com.aipo.orm.model.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.account.EipMCompany;

/**
 * Class _EipMMybox was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipMMybox extends CayenneDataObject {

    public static final String AIPO_ID_PROPERTY = "aipoId";
    public static final String AIPO_PASSWD_PROPERTY = "aipoPasswd";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_MCOMPANY_PROPERTY = "eipMCompany";

    public static final String MYBOX_ID_PK_COLUMN = "MYBOX_ID";

    public void setAipoId(String aipoId) {
        writeProperty("aipoId", aipoId);
    }
    public String getAipoId() {
        return (String)readProperty("aipoId");
    }

    public void setAipoPasswd(String aipoPasswd) {
        writeProperty("aipoPasswd", aipoPasswd);
    }
    public String getAipoPasswd() {
        return (String)readProperty("aipoPasswd");
    }

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setEipMCompany(EipMCompany eipMCompany) {
        setToOneTarget("eipMCompany", eipMCompany, true);
    }

    public EipMCompany getEipMCompany() {
        return (EipMCompany)readProperty("eipMCompany");
    }


}
