package com.aipo.orm.model.portlet.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTWorkflowCategory;
import com.aipo.orm.model.portlet.EipTWorkflowRequest;

/**
 * Class _EipTWorkflowRoute was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTWorkflowRoute extends CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String NOTE_PROPERTY = "note";
    public static final String ROUTE_PROPERTY = "route";
    public static final String ROUTE_NAME_PROPERTY = "routeName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TWORKFLOW_CATEGORY_PROPERTY = "eipTWorkflowCategory";
    public static final String EIP_TWORKFLOW_REQUEST_PROPERTY = "eipTWorkflowRequest";

    public static final String ROUTE_ID_PK_COLUMN = "ROUTE_ID";

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setRoute(String route) {
        writeProperty("route", route);
    }
    public String getRoute() {
        return (String)readProperty("route");
    }

    public void setRouteName(String routeName) {
        writeProperty("routeName", routeName);
    }
    public String getRouteName() {
        return (String)readProperty("routeName");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void addToEipTWorkflowCategory(EipTWorkflowCategory obj) {
        addToManyTarget("eipTWorkflowCategory", obj, true);
    }
    public void removeFromEipTWorkflowCategory(EipTWorkflowCategory obj) {
        removeToManyTarget("eipTWorkflowCategory", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTWorkflowCategory> getEipTWorkflowCategory() {
        return (List<EipTWorkflowCategory>)readProperty("eipTWorkflowCategory");
    }


    public void addToEipTWorkflowRequest(EipTWorkflowRequest obj) {
        addToManyTarget("eipTWorkflowRequest", obj, true);
    }
    public void removeFromEipTWorkflowRequest(EipTWorkflowRequest obj) {
        removeToManyTarget("eipTWorkflowRequest", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTWorkflowRequest> getEipTWorkflowRequest() {
        return (List<EipTWorkflowRequest>)readProperty("eipTWorkflowRequest");
    }


}
