package com.aipo.orm.model.portlet.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTTodoCategory;
import com.aipo.orm.model.security.TurbineUser;

/**
 * Class _EipTTodo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTTodo extends CayenneDataObject {

    public static final String ADDON_SCHEDULE_FLG_PROPERTY = "addonScheduleFlg";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String END_DATE_PROPERTY = "endDate";
    public static final String NOTE_PROPERTY = "note";
    public static final String PRIORITY_PROPERTY = "priority";
    public static final String PUBLIC_FLAG_PROPERTY = "publicFlag";
    public static final String START_DATE_PROPERTY = "startDate";
    public static final String STATE_PROPERTY = "state";
    public static final String TODO_NAME_PROPERTY = "todoName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TTODO_CATEGORY_PROPERTY = "eipTTodoCategory";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String TODO_ID_PK_COLUMN = "TODO_ID";

    public void setAddonScheduleFlg(String addonScheduleFlg) {
        writeProperty("addonScheduleFlg", addonScheduleFlg);
    }
    public String getAddonScheduleFlg() {
        return (String)readProperty("addonScheduleFlg");
    }

    public void setCreateDate(Date createDate) {
        writeProperty("createDate", createDate);
    }
    public Date getCreateDate() {
        return (Date)readProperty("createDate");
    }

    public void setEndDate(Date endDate) {
        writeProperty("endDate", endDate);
    }
    public Date getEndDate() {
        return (Date)readProperty("endDate");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setPriority(Short priority) {
        writeProperty("priority", priority);
    }
    public Short getPriority() {
        return (Short)readProperty("priority");
    }

    public void setPublicFlag(String publicFlag) {
        writeProperty("publicFlag", publicFlag);
    }
    public String getPublicFlag() {
        return (String)readProperty("publicFlag");
    }

    public void setStartDate(Date startDate) {
        writeProperty("startDate", startDate);
    }
    public Date getStartDate() {
        return (Date)readProperty("startDate");
    }

    public void setState(Short state) {
        writeProperty("state", state);
    }
    public Short getState() {
        return (Short)readProperty("state");
    }

    public void setTodoName(String todoName) {
        writeProperty("todoName", todoName);
    }
    public String getTodoName() {
        return (String)readProperty("todoName");
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty("updateDate");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setEipTTodoCategory(EipTTodoCategory eipTTodoCategory) {
        setToOneTarget("eipTTodoCategory", eipTTodoCategory, true);
    }

    public EipTTodoCategory getEipTTodoCategory() {
        return (EipTTodoCategory)readProperty("eipTTodoCategory");
    }


    public void setTurbineUser(TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public TurbineUser getTurbineUser() {
        return (TurbineUser)readProperty("turbineUser");
    }


}
