package com.aipo.orm.model.portlet.auto;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTCabinetFolder;

/**
 * Class _EipTCabinetFolderMap was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EipTCabinetFolderMap extends CayenneDataObject {

    public static final String STATUS_PROPERTY = "status";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TCABINET_FOLDER_PROPERTY = "eipTCabinetFolder";

    public static final String ID_PK_COLUMN = "ID";

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setEipTCabinetFolder(EipTCabinetFolder eipTCabinetFolder) {
        setToOneTarget("eipTCabinetFolder", eipTCabinetFolder, true);
    }

    public EipTCabinetFolder getEipTCabinetFolder() {
        return (EipTCabinetFolder)readProperty("eipTCabinetFolder");
    }


}
