package com.aipo.orm.model.portlet.auto;

/** Class _EipTAddressbookGroupMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTAddressbookGroupMap extends org.apache.cayenne.CayenneDataObject {

    public static final String ADDRESS_ID_PROPERTY = "addressId";
    public static final String EIP_MADDRESSBOOK_PROPERTY = "eipMAddressbook";
    public static final String EIP_TADDRESS_GROUP_PROPERTY = "eipTAddressGroup";

    public static final String ID_PK_COLUMN = "ID";

    public void setAddressId(Integer addressId) {
        writeProperty("addressId", addressId);
    }
    public Integer getAddressId() {
        return (Integer)readProperty("addressId");
    }
    
    
    public void setEipMAddressbook(com.aipo.orm.model.portlet.EipMAddressbook eipMAddressbook) {
        setToOneTarget("eipMAddressbook", eipMAddressbook, true);
    }

    public com.aipo.orm.model.portlet.EipMAddressbook getEipMAddressbook() {
        return (com.aipo.orm.model.portlet.EipMAddressbook)readProperty("eipMAddressbook");
    } 
    
    
    public void setEipTAddressGroup(com.aipo.orm.model.portlet.EipMAddressGroup eipTAddressGroup) {
        setToOneTarget("eipTAddressGroup", eipTAddressGroup, true);
    }

    public com.aipo.orm.model.portlet.EipMAddressGroup getEipTAddressGroup() {
        return (com.aipo.orm.model.portlet.EipMAddressGroup)readProperty("eipTAddressGroup");
    } 
    
    
}
