/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2011 Aimluck,Inc.
 * http://www.aipo.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aipo.orm.model.security.auto;

import java.util.List;

/** Class _TurbineGroup was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TurbineGroup extends org.apache.cayenne.CayenneDataObject {

    public static final String GROUP_ALIAS_NAME_PROPERTY = "groupAliasName";
    public static final String GROUP_NAME_PROPERTY = "groupName";
    public static final String OBJECTDATA_PROPERTY = "objectdata";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String PUBLIC_FLAG_PROPERTY = "publicFlag";
    public static final String EIP_FACILITY_GROUP_PROPERTY = "eipFacilityGroup";
    public static final String EIP_MPOST_PROPERTY = "eipMPost";
    public static final String TURBINE_USER_GROUP_ROLE_PROPERTY = "turbineUserGroupRole";

    public static final String GROUP_ID_PK_COLUMN = "GROUP_ID";

    public void setGroupAliasName(String groupAliasName) {
        writeProperty("groupAliasName", groupAliasName);
    }
    public String getGroupAliasName() {
        return (String)readProperty("groupAliasName");
    }
    
    
    public void setGroupName(String groupName) {
        writeProperty("groupName", groupName);
    }
    public String getGroupName() {
        return (String)readProperty("groupName");
    }
    
    
    public void setObjectdata(byte[] objectdata) {
        writeProperty("objectdata", objectdata);
    }
    public byte[] getObjectdata() {
        return (byte[])readProperty("objectdata");
    }
    
    
    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }
    
    
    public void setPublicFlag(String publicFlag) {
        writeProperty("publicFlag", publicFlag);
    }
    public String getPublicFlag() {
        return (String)readProperty("publicFlag");
    }
    
    
    public void addToEipFacilityGroup(com.aipo.orm.model.portlet.EipFacilityGroup obj) {
        addToManyTarget("eipFacilityGroup", obj, true);
    }
    public void removeFromEipFacilityGroup(com.aipo.orm.model.portlet.EipFacilityGroup obj) {
        removeToManyTarget("eipFacilityGroup", obj, true);
    }
    public List getEipFacilityGroup() {
        return (List)readProperty("eipFacilityGroup");
    }
    
    
    public void setEipMPost(com.aipo.orm.model.account.EipMPost eipMPost) {
        setToOneTarget("eipMPost", eipMPost, true);
    }

    public com.aipo.orm.model.account.EipMPost getEipMPost() {
        return (com.aipo.orm.model.account.EipMPost)readProperty("eipMPost");
    } 
    
    
    public void addToTurbineUserGroupRole(com.aipo.orm.model.security.TurbineUserGroupRole obj) {
        addToManyTarget("turbineUserGroupRole", obj, true);
    }
    public void removeFromTurbineUserGroupRole(com.aipo.orm.model.security.TurbineUserGroupRole obj) {
        removeToManyTarget("turbineUserGroupRole", obj, true);
    }
    public List getTurbineUserGroupRole() {
        return (List)readProperty("turbineUserGroupRole");
    }
    
    
}
