package com.aipo.orm.model.security.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.account.EipMPost;
import com.aipo.orm.model.portlet.EipFacilityGroup;
import com.aipo.orm.model.security.TurbineUserGroupRole;

/**
 * Class _TurbineGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TurbineGroup extends CayenneDataObject {

    public static final String GROUP_ALIAS_NAME_PROPERTY = "groupAliasName";
    public static final String GROUP_NAME_PROPERTY = "groupName";
    public static final String OBJECTDATA_PROPERTY = "objectdata";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String PUBLIC_FLAG_PROPERTY = "publicFlag";
    public static final String EIP_FACILITY_GROUP_PROPERTY = "eipFacilityGroup";
    public static final String EIP_MPOST_PROPERTY = "eipMPost";
    public static final String TURBINE_USER_GROUP_ROLE_PROPERTY = "turbineUserGroupRole";

    public static final String GROUP_ID_PK_COLUMN = "GROUP_ID";

    public void setGroupAliasName(String groupAliasName) {
        writeProperty("groupAliasName", groupAliasName);
    }
    public String getGroupAliasName() {
        return (String)readProperty("groupAliasName");
    }

    public void setGroupName(String groupName) {
        writeProperty("groupName", groupName);
    }
    public String getGroupName() {
        return (String)readProperty("groupName");
    }

    public void setObjectdata(byte[] objectdata) {
        writeProperty("objectdata", objectdata);
    }
    public byte[] getObjectdata() {
        return (byte[])readProperty("objectdata");
    }

    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }

    public void setPublicFlag(String publicFlag) {
        writeProperty("publicFlag", publicFlag);
    }
    public String getPublicFlag() {
        return (String)readProperty("publicFlag");
    }

    public void addToEipFacilityGroup(EipFacilityGroup obj) {
        addToManyTarget("eipFacilityGroup", obj, true);
    }
    public void removeFromEipFacilityGroup(EipFacilityGroup obj) {
        removeToManyTarget("eipFacilityGroup", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipFacilityGroup> getEipFacilityGroup() {
        return (List<EipFacilityGroup>)readProperty("eipFacilityGroup");
    }


    public void setEipMPost(EipMPost eipMPost) {
        setToOneTarget("eipMPost", eipMPost, true);
    }

    public EipMPost getEipMPost() {
        return (EipMPost)readProperty("eipMPost");
    }


    public void addToTurbineUserGroupRole(TurbineUserGroupRole obj) {
        addToManyTarget("turbineUserGroupRole", obj, true);
    }
    public void removeFromTurbineUserGroupRole(TurbineUserGroupRole obj) {
        removeToManyTarget("turbineUserGroupRole", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TurbineUserGroupRole> getTurbineUserGroupRole() {
        return (List<TurbineUserGroupRole>)readProperty("turbineUserGroupRole");
    }


}
