package com.aipo.orm.model.security.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.portlet.EipTScheduleMap;
import com.aipo.orm.model.security.TurbineGroup;
import com.aipo.orm.model.security.TurbineRole;
import com.aipo.orm.model.security.TurbineUser;

/**
 * Class _TurbineUserGroupRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TurbineUserGroupRole extends CayenneDataObject {

    public static final String EIP_TSCHEDULE_MAP_PROPERTY = "eipTScheduleMap";
    public static final String TURBINE_GROUP_PROPERTY = "turbineGroup";
    public static final String TURBINE_ROLE_PROPERTY = "turbineRole";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String ID_PK_COLUMN = "ID";

    public void addToEipTScheduleMap(EipTScheduleMap obj) {
        addToManyTarget("eipTScheduleMap", obj, true);
    }
    public void removeFromEipTScheduleMap(EipTScheduleMap obj) {
        removeToManyTarget("eipTScheduleMap", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EipTScheduleMap> getEipTScheduleMap() {
        return (List<EipTScheduleMap>)readProperty("eipTScheduleMap");
    }


    public void setTurbineGroup(TurbineGroup turbineGroup) {
        setToOneTarget("turbineGroup", turbineGroup, true);
    }

    public TurbineGroup getTurbineGroup() {
        return (TurbineGroup)readProperty("turbineGroup");
    }


    public void setTurbineRole(TurbineRole turbineRole) {
        setToOneTarget("turbineRole", turbineRole, true);
    }

    public TurbineRole getTurbineRole() {
        return (TurbineRole)readProperty("turbineRole");
    }


    public void setTurbineUser(TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public TurbineUser getTurbineUser() {
        return (TurbineUser)readProperty("turbineUser");
    }


}
