package com.aipo.orm.model.security.auto;

/** Class _TurbineRolePermission was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TurbineRolePermission extends org.apache.cayenne.CayenneDataObject {

    public static final String TURBINE_PERMISSION_PROPERTY = "turbinePermission";
    public static final String TURBINE_ROLE_PROPERTY = "turbineRole";

    public static final String PERMISSION_ID_PK_COLUMN = "PERMISSION_ID";
    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public void setTurbinePermission(com.aipo.orm.model.security.TurbinePermission turbinePermission) {
        setToOneTarget("turbinePermission", turbinePermission, true);
    }

    public com.aipo.orm.model.security.TurbinePermission getTurbinePermission() {
        return (com.aipo.orm.model.security.TurbinePermission)readProperty("turbinePermission");
    } 
    
    
    public void setTurbineRole(com.aipo.orm.model.security.TurbineRole turbineRole) {
        setToOneTarget("turbineRole", turbineRole, true);
    }

    public com.aipo.orm.model.security.TurbineRole getTurbineRole() {
        return (com.aipo.orm.model.security.TurbineRole)readProperty("turbineRole");
    } 
    
    
}
