/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2011 Aimluck,Inc.
 * http://www.aipo.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aipo.orm.model.security.auto;

import java.util.List;

/** Class _TurbineUser was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TurbineUser extends org.apache.cayenne.CayenneDataObject {

    public static final String CELLULAR_MAIL_PROPERTY = "cellularMail";
    public static final String CELLULAR_PHONE_PROPERTY = "cellularPhone";
    public static final String CELLULAR_UID_PROPERTY = "cellularUid";
    public static final String COMPANY_ID_PROPERTY = "companyId";
    public static final String CONFIRM_VALUE_PROPERTY = "confirmValue";
    public static final String CREATED_PROPERTY = "created";
    public static final String CREATED_USER_ID_PROPERTY = "createdUserId";
    public static final String DISABLED_PROPERTY = "disabled";
    public static final String EMAIL_PROPERTY = "email";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String FIRST_NAME_KANA_PROPERTY = "firstNameKana";
    public static final String IN_TELEPHONE_PROPERTY = "inTelephone";
    public static final String LAST_LOGIN_PROPERTY = "lastLogin";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String LAST_NAME_KANA_PROPERTY = "lastNameKana";
    public static final String LOGIN_NAME_PROPERTY = "loginName";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String OBJECTDATA_PROPERTY = "objectdata";
    public static final String OUT_TELEPHONE_PROPERTY = "outTelephone";
    public static final String PASSWORD_CHANGED_PROPERTY = "passwordChanged";
    public static final String PASSWORD_VALUE_PROPERTY = "passwordValue";
    public static final String PHOTO_PROPERTY = "photo";
    public static final String POSITION_ID_PROPERTY = "positionId";
    public static final String UPDATED_USER_ID_PROPERTY = "updatedUserId";
    public static final String EIP_MUSER_POSITION_PROPERTY = "eipMUserPosition";
    public static final String EIP_TACL_USER_ROLE_MAPS_PROPERTY = "eipTAclUserRoleMaps";
    public static final String EIP_TEVENTLOG_PROPERTY = "eipTEventlog";
    public static final String EIP_TMSGBOARD_CATEGORY_PROPERTY = "eipTMsgboardCategory";
    public static final String EIP_TTODO_PROPERTY = "eipTTodo";
    public static final String TURBINE_USER_GROUP_ROLE_PROPERTY = "turbineUserGroupRole";

    public static final String USER_ID_PK_COLUMN = "USER_ID";

    public void setCellularMail(String cellularMail) {
        writeProperty("cellularMail", cellularMail);
    }
    public String getCellularMail() {
        return (String)readProperty("cellularMail");
    }
    
    
    public void setCellularPhone(String cellularPhone) {
        writeProperty("cellularPhone", cellularPhone);
    }
    public String getCellularPhone() {
        return (String)readProperty("cellularPhone");
    }
    
    
    public void setCellularUid(String cellularUid) {
        writeProperty("cellularUid", cellularUid);
    }
    public String getCellularUid() {
        return (String)readProperty("cellularUid");
    }
    
    
    public void setCompanyId(Integer companyId) {
        writeProperty("companyId", companyId);
    }
    public Integer getCompanyId() {
        return (Integer)readProperty("companyId");
    }
    
    
    public void setConfirmValue(String confirmValue) {
        writeProperty("confirmValue", confirmValue);
    }
    public String getConfirmValue() {
        return (String)readProperty("confirmValue");
    }
    
    
    public void setCreated(java.util.Date created) {
        writeProperty("created", created);
    }
    public java.util.Date getCreated() {
        return (java.util.Date)readProperty("created");
    }
    
    
    public void setCreatedUserId(Integer createdUserId) {
        writeProperty("createdUserId", createdUserId);
    }
    public Integer getCreatedUserId() {
        return (Integer)readProperty("createdUserId");
    }
    
    
    public void setDisabled(String disabled) {
        writeProperty("disabled", disabled);
    }
    public String getDisabled() {
        return (String)readProperty("disabled");
    }
    
    
    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }
    
    
    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }
    
    
    public void setFirstNameKana(String firstNameKana) {
        writeProperty("firstNameKana", firstNameKana);
    }
    public String getFirstNameKana() {
        return (String)readProperty("firstNameKana");
    }
    
    
    public void setInTelephone(String inTelephone) {
        writeProperty("inTelephone", inTelephone);
    }
    public String getInTelephone() {
        return (String)readProperty("inTelephone");
    }
    
    
    public void setLastLogin(java.util.Date lastLogin) {
        writeProperty("lastLogin", lastLogin);
    }
    public java.util.Date getLastLogin() {
        return (java.util.Date)readProperty("lastLogin");
    }
    
    
    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }
    
    
    public void setLastNameKana(String lastNameKana) {
        writeProperty("lastNameKana", lastNameKana);
    }
    public String getLastNameKana() {
        return (String)readProperty("lastNameKana");
    }
    
    
    public void setLoginName(String loginName) {
        writeProperty("loginName", loginName);
    }
    public String getLoginName() {
        return (String)readProperty("loginName");
    }
    
    
    public void setModified(java.util.Date modified) {
        writeProperty("modified", modified);
    }
    public java.util.Date getModified() {
        return (java.util.Date)readProperty("modified");
    }
    
    
    public void setObjectdata(byte[] objectdata) {
        writeProperty("objectdata", objectdata);
    }
    public byte[] getObjectdata() {
        return (byte[])readProperty("objectdata");
    }
    
    
    public void setOutTelephone(String outTelephone) {
        writeProperty("outTelephone", outTelephone);
    }
    public String getOutTelephone() {
        return (String)readProperty("outTelephone");
    }
    
    
    public void setPasswordChanged(java.util.Date passwordChanged) {
        writeProperty("passwordChanged", passwordChanged);
    }
    public java.util.Date getPasswordChanged() {
        return (java.util.Date)readProperty("passwordChanged");
    }
    
    
    public void setPasswordValue(String passwordValue) {
        writeProperty("passwordValue", passwordValue);
    }
    public String getPasswordValue() {
        return (String)readProperty("passwordValue");
    }
    
    
    public void setPhoto(byte[] photo) {
        writeProperty("photo", photo);
    }
    public byte[] getPhoto() {
        return (byte[])readProperty("photo");
    }
    
    
    public void setPositionId(Integer positionId) {
        writeProperty("positionId", positionId);
    }
    public Integer getPositionId() {
        return (Integer)readProperty("positionId");
    }
    
    
    public void setUpdatedUserId(Integer updatedUserId) {
        writeProperty("updatedUserId", updatedUserId);
    }
    public Integer getUpdatedUserId() {
        return (Integer)readProperty("updatedUserId");
    }
    
    
    public void setEipMUserPosition(com.aipo.orm.model.account.EipMUserPosition eipMUserPosition) {
        setToOneTarget("eipMUserPosition", eipMUserPosition, true);
    }

    public com.aipo.orm.model.account.EipMUserPosition getEipMUserPosition() {
        return (com.aipo.orm.model.account.EipMUserPosition)readProperty("eipMUserPosition");
    } 
    
    
    public void addToEipTAclUserRoleMaps(com.aipo.orm.model.account.EipTAclUserRoleMap obj) {
        addToManyTarget("eipTAclUserRoleMaps", obj, true);
    }
    public void removeFromEipTAclUserRoleMaps(com.aipo.orm.model.account.EipTAclUserRoleMap obj) {
        removeToManyTarget("eipTAclUserRoleMaps", obj, true);
    }
    public List getEipTAclUserRoleMaps() {
        return (List)readProperty("eipTAclUserRoleMaps");
    }
    
    
    public void addToEipTEventlog(com.aipo.orm.model.portlet.EipTEventlog obj) {
        addToManyTarget("eipTEventlog", obj, true);
    }
    public void removeFromEipTEventlog(com.aipo.orm.model.portlet.EipTEventlog obj) {
        removeToManyTarget("eipTEventlog", obj, true);
    }
    public List getEipTEventlog() {
        return (List)readProperty("eipTEventlog");
    }
    
    
    public void addToEipTMsgboardCategory(com.aipo.orm.model.portlet.EipTMsgboardCategory obj) {
        addToManyTarget("eipTMsgboardCategory", obj, true);
    }
    public void removeFromEipTMsgboardCategory(com.aipo.orm.model.portlet.EipTMsgboardCategory obj) {
        removeToManyTarget("eipTMsgboardCategory", obj, true);
    }
    public List getEipTMsgboardCategory() {
        return (List)readProperty("eipTMsgboardCategory");
    }
    
    
    public void addToEipTTodo(com.aipo.orm.model.portlet.EipTTodo obj) {
        addToManyTarget("eipTTodo", obj, true);
    }
    public void removeFromEipTTodo(com.aipo.orm.model.portlet.EipTTodo obj) {
        removeToManyTarget("eipTTodo", obj, true);
    }
    public List getEipTTodo() {
        return (List)readProperty("eipTTodo");
    }
    
    
    public void addToTurbineUserGroupRole(com.aipo.orm.model.security.TurbineUserGroupRole obj) {
        addToManyTarget("turbineUserGroupRole", obj, true);
    }
    public void removeFromTurbineUserGroupRole(com.aipo.orm.model.security.TurbineUserGroupRole obj) {
        removeToManyTarget("turbineUserGroupRole", obj, true);
    }
    public List getTurbineUserGroupRole() {
        return (List)readProperty("turbineUserGroupRole");
    }
    
    
}
