package com.aipo.orm.model.security.auto;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.security.TurbinePermission;
import com.aipo.orm.model.security.TurbineRole;

/**
 * Class _TurbineRolePermission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TurbineRolePermission extends CayenneDataObject {

    public static final String TURBINE_PERMISSION_PROPERTY = "turbinePermission";
    public static final String TURBINE_ROLE_PROPERTY = "turbineRole";

    public static final String PERMISSION_ID_PK_COLUMN = "PERMISSION_ID";
    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public void setTurbinePermission(TurbinePermission turbinePermission) {
        setToOneTarget("turbinePermission", turbinePermission, true);
    }

    public TurbinePermission getTurbinePermission() {
        return (TurbinePermission)readProperty("turbinePermission");
    }


    public void setTurbineRole(TurbineRole turbineRole) {
        setToOneTarget("turbineRole", turbineRole, true);
    }

    public TurbineRole getTurbineRole() {
        return (TurbineRole)readProperty("turbineRole");
    }


}
