package com.aipo.orm.model.security.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.aipo.orm.model.security.TurbineRolePermission;
import com.aipo.orm.model.security.TurbineUserGroupRole;

/**
 * Class _TurbineRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TurbineRole extends CayenneDataObject {

    public static final String OBJECTDATA_PROPERTY = "objectdata";
    public static final String ROLE_NAME_PROPERTY = "roleName";
    public static final String TURBINE_ROLE_PERMISSION_PROPERTY = "turbineRolePermission";
    public static final String TURBINE_USER_GROUP_ROLE_PROPERTY = "turbineUserGroupRole";

    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public void setObjectdata(byte[] objectdata) {
        writeProperty("objectdata", objectdata);
    }
    public byte[] getObjectdata() {
        return (byte[])readProperty("objectdata");
    }

    public void setRoleName(String roleName) {
        writeProperty("roleName", roleName);
    }
    public String getRoleName() {
        return (String)readProperty("roleName");
    }

    public void addToTurbineRolePermission(TurbineRolePermission obj) {
        addToManyTarget("turbineRolePermission", obj, true);
    }
    public void removeFromTurbineRolePermission(TurbineRolePermission obj) {
        removeToManyTarget("turbineRolePermission", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TurbineRolePermission> getTurbineRolePermission() {
        return (List<TurbineRolePermission>)readProperty("turbineRolePermission");
    }


    public void addToTurbineUserGroupRole(TurbineUserGroupRole obj) {
        addToManyTarget("turbineUserGroupRole", obj, true);
    }
    public void removeFromTurbineUserGroupRole(TurbineUserGroupRole obj) {
        removeToManyTarget("turbineUserGroupRole", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TurbineUserGroupRole> getTurbineUserGroupRole() {
        return (List<TurbineUserGroupRole>)readProperty("turbineUserGroupRole");
    }


}
