/*
 * Aipo is a groupware program developed by Aimluck,Inc.
 * Copyright (C) 2004-2011 Aimluck,Inc.
 * http://www.aipo.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.aipo.orm.model.security.auto;

/** Class _TurbineRolePermission was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TurbineRolePermission extends org.apache.cayenne.CayenneDataObject {

    public static final String TURBINE_PERMISSION_PROPERTY = "turbinePermission";
    public static final String TURBINE_ROLE_PROPERTY = "turbineRole";

    public static final String PERMISSION_ID_PK_COLUMN = "PERMISSION_ID";
    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public void setTurbinePermission(com.aipo.orm.model.security.TurbinePermission turbinePermission) {
        setToOneTarget("turbinePermission", turbinePermission, true);
    }

    public com.aipo.orm.model.security.TurbinePermission getTurbinePermission() {
        return (com.aipo.orm.model.security.TurbinePermission)readProperty("turbinePermission");
    } 
    
    
    public void setTurbineRole(com.aipo.orm.model.security.TurbineRole turbineRole) {
        setToOneTarget("turbineRole", turbineRole, true);
    }

    public com.aipo.orm.model.security.TurbineRole getTurbineRole() {
        return (com.aipo.orm.model.security.TurbineRole)readProperty("turbineRole");
    } 
    
    
}
