package com.aipo.orm.model.security.auto;

import java.util.List;

/** Class _TurbineUserGroupRole was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TurbineUserGroupRole extends org.apache.cayenne.CayenneDataObject {

    public static final String EIP_TSCHEDULE_MAP_PROPERTY = "eipTScheduleMap";
    public static final String TURBINE_GROUP_PROPERTY = "turbineGroup";
    public static final String TURBINE_ROLE_PROPERTY = "turbineRole";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String ID_PK_COLUMN = "ID";

    public void addToEipTScheduleMap(com.aipo.orm.model.portlet.EipTScheduleMap obj) {
        addToManyTarget("eipTScheduleMap", obj, true);
    }
    public void removeFromEipTScheduleMap(com.aipo.orm.model.portlet.EipTScheduleMap obj) {
        removeToManyTarget("eipTScheduleMap", obj, true);
    }
    public List getEipTScheduleMap() {
        return (List)readProperty("eipTScheduleMap");
    }
    
    
    public void setTurbineGroup(com.aipo.orm.model.security.TurbineGroup turbineGroup) {
        setToOneTarget("turbineGroup", turbineGroup, true);
    }

    public com.aipo.orm.model.security.TurbineGroup getTurbineGroup() {
        return (com.aipo.orm.model.security.TurbineGroup)readProperty("turbineGroup");
    } 
    
    
    public void setTurbineRole(com.aipo.orm.model.security.TurbineRole turbineRole) {
        setToOneTarget("turbineRole", turbineRole, true);
    }

    public com.aipo.orm.model.security.TurbineRole getTurbineRole() {
        return (com.aipo.orm.model.security.TurbineRole)readProperty("turbineRole");
    } 
    
    
    public void setTurbineUser(com.aipo.orm.model.security.TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public com.aipo.orm.model.security.TurbineUser getTurbineUser() {
        return (com.aipo.orm.model.security.TurbineUser)readProperty("turbineUser");
    } 
    
    
}
